name: Update Builder on Docker Hub

on:
  push:
    paths:
      - 'builder.toml'

jobs:
  update-builder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Checkout Code
    - uses: actions/setup-go@v5
      with:
          go-version: "1.20"

    - name: Set up Pack CLI
      uses: paketo-buildpacks/github-config/actions/setup-pack@main
      with:
        version: 0.32.1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Builder to Docker Hub
      run: |
        pack builder create ${{ secrets.DOCKER_USERNAME }}/initializ-builder --config ./builder.toml
        pack build ${{ secrets.DOCKER_USERNAME }}/initializ-builder --builder ${{ secrets.DOCKER_USERNAME }}/initializ-builder --no-cache
        docker push ${{ secrets.DOCKER_USERNAME }}/initializ-builder:latest
