Description  = "Initializ Distrolesss base image with buildpacks for Go, NodeJS, Python, Java, .NET Core, PHP, Ruby, Apache HTTPD, NGINX and Procfile"
 
[[buildpacks]]
  uri = "public.ecr.aws/initializ/buildpack/go@sha256:b362b2931939f45f76611f6bf1da147715583119267f0c9ce6773fc0d2fbb348"
  version = "1.0.2"
 
[[buildpacks]]
  uri = "public.ecr.aws/initializ/buildpack/nodejs@sha256:08da8f9143ce909398fe3fc469e1cf62a08ceaadbe9029f42db33f1d7f9e8450"
  version = "2.2.3"
 
[[buildpacks]]
  uri = "public.ecr.aws/initializ/buildpack/python@sha256:36ce50cbc407ef025200fe0d3daa730f67fe4ac7a8ca39ab6be1fafe616f4023"
  version = "4.0.2"
 
[[buildpacks]]
  uri = "public.ecr.aws/initializ/buildpack/java@sha256:aec4a0d573bf9c5a309c28482710fbfe1526c7f96b8a95cce37b175c9e9ca5cf"
  version = "2.0.2"
 
[[buildpacks]]
  uri = "docker://public.ecr.aws/initializ/buildpack/dotnetfull@sha256:fea8accdd0fb78ba64d1829a296fd6a397b8802932cc4ad78efad4095b336cf4"
  version = "1.0.9"  
 
[[buildpacks]]
  uri = "docker://public.ecr.aws/initializ/buildpack/php@sha256:f549166e43e2b84a2159cccc6ac9d1911a50a9844f366cde004e54311e358d6f"
  version = "1.0.4"   

[[buildpacks]]
  uri = "docker://public.ecr.aws/initializ/buildpack/web-servers@sha256:1259c10adde1e5a1731b576959d88be35cf928fc43a1aec97e6d7328652fa150"
  version = "1.0.2" 

[[buildpacks]]
  uri = "public.ecr.aws/initializ/buildpack/java-native-image@sha256:ac755349ce60a23389fe3fb65925ccafc3d407a619a190c4aa6ed72ed56f89f8"
  version = "9.0.1" 

[[buildpacks]]
  uri = "public.ecr.aws/initializ/buildpack/procfile@sha256:f9f9558b1ead4e8fc781b5e62df54eac074c2a240bab99737b4c824c6e6f3712"
  version = "5.6.10" 
 
[[order]]
 
  [[order.group]]
    id = "initializ-buildpacks/go"
    version = "1.0.2"
 
[[order]]
 
  [[order.group]]
    id = "initializ-buildpacks/nodejs"
    version = "2.2.3"
 
[[order]]
 
  [[order.group]]
    id = "initializ-buildpacks/python"
    version = "4.0.2"
 
 
[[order]]
 
  [[order.group]]
    id = "initializ-buildpacks/java"
    version = "2.0.2"
 
[[order]]
 
  [[order.group]]
    id = "initializ-buildpacks/dotnet-core"
    version = "1.0.9"
 
[[order]]
 
  [[order.group]]
    id = "initializ-buildpacks/php"
    version = "1.0.4"    

[[order]]
 
  [[order.group]]
    id = "initializ-buildpacks/web-servers"
    version = "1.0.2" 

[[order]]
 
  [[order.group]]
    id = "initializ-buildpacks/java-native-image"
    version = "9.0.1"

[[order]]
 
  [[order.group]]
    id = "initializ-buildpacks/procfile"
    version = "5.6.10"
 

# Base images used to create the builder
[stack]
  build-image = "07f7e2512710"
  id = "Initializ Distroless Stack"
  run-image = "07f7e2512710"
  run-image-mirrors = []
