description = "Initializ Securepack for Python"

[[buildpacks]]
  uri = "index.docker.io/initializbuildpacks/python@sha256:271a0f00e921dccd76883dfe52b126bf02648b2125e1890e737cb83074bced43"
  version = "4.0.3"

[[order]]
 
  [[order.group]]
    id = "initializ-buildpacks/python"
    version = "4.0.3"

# Base images used to create the builder
[stack]
  build-image = "initializbuildpacks/python-build-image-labeled:latest"
  id = "Initializ Distroless Stack"
  run-image = "initializbuildpacks/python-run-image-labeled:latest"
  run-image-mirrors = []
