description = "Initializ Securepack for Python, Apache HTTPD, NGINX and Procfile"

[[buildpacks]]
  uri = "index.docker.io/initializbuildpacks/python@sha256:271a0f00e921dccd76883dfe52b126bf02648b2125e1890e737cb83074bced43"
  version = "4.0.3"

[[order]]
 
  [[order.group]]
    id = "initializ-buildpacks/python"
    version = "4.0.3"

# Base images used to create the builder
[stack]
  build-image = "pythonsecurepacks/build:1.0.0"
  id = "Initializ Distroless Stack"
  run-image = "pythonsecurepacks/run:1.0.0"
  run-image-mirrors = []