on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to Release'
        required: true
        type: string
permissions:
      id-token: write # This is required for AWS OIDC connection
      contents: read # This is required for actions/checkout

jobs:
  image-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  


      - name: Build  image
        run: |
          docker build -t initializbuildpacks/${{ inputs.image }}:latest -f initializbuildpacks/${{ inputs.image }}/Dockerfile .
          docker tag initializbuildpacks/${{ inputs.image }}:latest initializbuildpacks/${{ inputs.image }}:latest
          
      - name: Tag and push Docker image to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          REPOSITORY: ${{ inputs.image }}
        run: |
          docker tag initializbuildpacks/${{ inputs.image }}:latest initializbuildpacks/${{ inputs.image }}:latest
          docker push initializbuildpacks/${{ inputs.image }}:latest
      - uses: sigstore/cosign-installer@11086d25041f77fe8fe7b9ea4e48e3b9192b8f19 # v3.1.2
      - name: Sign the images
        run: |
          cosign sign \
            --yes initializbuildpacks/${{ inputs.image }}:latest
      - name: Verify the pushed tags
        run: | 
          cosign verify \
          initializbuildpacks/${{ inputs.image }}:latest \
          --certificate-identity https://github.com/naveeninitializ/automation/.github/workflows/dockerimagerelease.yaml@refs/heads/master \
          --certificate-oidc-issuer https://token.actions.githubusercontent.com | jq