on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Enter the name of the Docker image to release'
        required: true
        type: string

jobs:
  docker-image-release:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Create & Push Minimal Image using apko
        id: apko
        uses: distroless/actions/apko-build@main
        with:
          config: initializbuildpacks/build-base/apko.yaml  # Corrected path here
          tag: ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image }}:latest

      # Remaining steps for Docker image release
