on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to Release'
        required: true
        type: string

jobs:
  image-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      # Remove the AWS specific steps and keys
      # - name: Configure AWS credentials from AWS account
      #   uses: aws-actions/configure-aws-credentials@v1

      # Replace this step with Docker Hub login
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create & Push Minimal Image using apko
        id: apko
        uses: distroless/actions/apko-build@main
        with:
          config: initializbuildpacks/build-base/apko.yaml
          tag: ${{ inputs.image }}:latest

      # Replace the ECR Public push with Docker Hub push
      - name: Push docker image to Docker Hub
        env:
          REGISTRY: docker.io
          REPOSITORY: ${{ inputs.image }}
        run: |
          docker load < output.tar
          docker tag build-base:${{ inputs.image }}-latest ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest

      # The rest of the workflow remains unchanged
      # ...