on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to Release'
        required: true
        type: string

jobs:
  image-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install Cosign
        uses: sigstore/cosign-installer@11086d25041f77fe8fe7b9ea4e48e3b9192b8f19 # v3.1.2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image }}:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image }}:latest

      - name: Sign the images
        run: |
          cosign sign \
            --yes ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image }}:latest

      - name: Verify the pushed tags
        run: |
          cosign verify \
            ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image }}:latest | jq

      - name: Attest SBOM
        run: |
          cosign attest \
            --yes --predicate sbom-x86_64.spdx.json --type spdxjson ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image }}:latest
