on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to Release'
        required: true
        type: string
      
jobs:
  image-release:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create & Push Minimal Image using apko
        id: apko
        uses: distroless/actions/apko-build@main
        with:
          config: initializbuildpacks/build-base/apko.yaml
          tag: initializbuildpacks/build-base:latest

      - name: Tag and push Docker image to Docker Hub
        run: |
          docker push initializbuildpacks/build-base:latest

      - uses: sigstore/cosign-installer@11086d25041f77fe8fe7b9ea4e48e3b9192b8f19 # v3.1.2
      - name: Sign the images
        run: |
          cosign sign \
            --yes initializbuildpacks/build-base:latest

      - name: Verify the pushed tags
        run: | 
          cosign verify \
          initializbuildpacks/build-base:latest \
          --certificate-identity https://github.com/initializ/secure-images/.github/workflows/release.yml@refs/heads/main \
          --certificate-oidc-issuer https://token.actions.githubusercontent.com | jq

      - name: Attest SBOM
        run: |
          cosign attest \
            --yes --predicate sbom-x86_64.spdx.json --type spdxjson initializbuildpacks/build-base:latest
