on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to Release'
        required: true
        type: string

permissions:
  id-token: write  # This is required for GH OIDC connection
  contents: read   # This is required for actions/checkout

jobs:
  image-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        id: login-dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create & Push Minimal Image using apko
        id: apko
        uses: distroless/actions/apko-build@main
        with:
          config: images/${{ inputs.image }}/apko.yaml
          tag: ${{ inputs.image }}:latest

      - name: Tag, and push docker image to Docker Hub
        env:
          REGISTRY: docker.io
          REPOSITORY: ${{ inputs.image }}
        run: |
          docker load < output.tar
          docker tag ${{ inputs.image }}:latest ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest

      - uses: sigstore/cosign-installer@v1 # v3.1.2 is not available anymore, use the latest v1

      - name: Sign the images
        run: |
          cosign sign \
            --yes ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest

      - name: Verify the pushed tags
        run: | 
          cosign verify \
          ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest \
          --certificate-identity https://github.com/<USERNAME>/<REPO>/.github/workflows/release.yml@refs/heads/<BRANCH> \
          --certificate-oidc-issuer https://token.actions.githubusercontent.com | jq

      - name: Attest SBOM
        run: |
          cosign attest \
            --yes --predicate sbom-x86_64.spdx.json --type spdxjson ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest